apiVersion: v1
kind: Service
metadata:
  name: quiz-distribution
  annotations:
    tailscale.com/hostname: "quiz-distribution"
    tailscale.com/expose: "true"
spec:
  type: NodePort
  ports:
    - port: 5003
      targetPort: 5003
      nodePort: 30503
      protocol: TCP
  selector:
    app: quiz-distribution
