apiVersion: v1
kind: Service
metadata:
  name: quiz-delivery
  annotations:
    tailscale.com/hostname: "quiz-delivery"
    tailscale.com/expose: "true"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: quiz-delivery
